'use client';

import React, { useState, useEffect } from 'react';
import { ComposableMap, Geographies, Geography, Marker, ZoomableGroup } from 'react-simple-maps';
import { MapPin, Globe } from 'lucide-react';

// Using local file for better reliability (High resolution 50m)
const geoUrl = "/world-50m.json";

export default function EuropeMap() {
  const [lcs, setLcs] = useState<any[]>([]);
  const [hoveredLC, setHoveredLC] = useState<any | null>(null);

  useEffect(() => {
    // Load the static JSON generated by our backend scraper
    fetch('/eestec-lcs.json')
      .then(res => res.json())
      .then(data => {
        // filter out branches that failed to geocode AND branches that are Suspended
        const activeBranches = data.filter((b: any) => 
          b.coords !== null && 
          (b.type === 'Local Committee' || b.type === 'Observer')
        );
        setLcs(activeBranches);
      })
      .catch(err => console.error("Error loading EESTEC LCs:", err));
  }, []);

  return (
    <div className="relative w-full aspect-[16/9] max-w-6xl mx-auto rounded-3xl overflow-hidden bg-white/5 border border-white/10 shadow-2xl flex items-center justify-center p-4">
      {/* Interactive Tooltip Container */}
      {hoveredLC && (
        <div className="absolute top-8 right-8 border p-5 rounded-2xl shadow-2xl z-20 pointer-events-none min-w-[280px]"
          style={{ background: '#111', borderColor: 'rgba(255,255,255,0.12)' }}>
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 rounded-full flex items-center justify-center shadow-lg"
              style={{ background: hoveredLC.type === 'Observer' ? '#333' : '#E8161B' }}>
              <MapPin className="text-white w-5 h-5" />
            </div>
            <div>
              <p className="text-xs font-black uppercase tracking-wider" style={{ color: 'rgba(255,255,255,0.5)' }}>
                {hoveredLC.type}
              </p>
              <h3 className="text-2xl font-black text-white">
                {hoveredLC.name}
              </h3>
            </div>
          </div>

          <p className="text-sm mb-4 pb-4" style={{ color: 'rgba(255,255,255,0.55)', borderBottom: '1px solid rgba(255,255,255,0.08)' }}>
            {hoveredLC.country}
          </p>

          <div className="space-y-2">
            {hoveredLC.website ? (
              <div className="flex items-center gap-2">
                <Globe className="w-4 h-4" style={{ color: 'rgba(255,255,255,0.4)' }} />
                <span className="text-sm truncate w-48" style={{ color: 'rgba(255,255,255,0.75)' }}>{hoveredLC.website}</span>
              </div>
            ) : (
              <div className="text-sm italic" style={{ color: 'rgba(255,255,255,0.35)' }}>Sin página web oficial</div>
            )}
          </div>
        </div>
      )}

      {/* Map Content */}
      <ComposableMap
        projection="geoAzimuthalEqualArea"
        projectionConfig={{
          rotate: [-20.0, -52.0, 0],
          center: [5, -3], // Adjust for perfect framing covering Europe & Turkey
          scale: 1100 // Slightly increased scale for better detail
        }}
        className="w-full h-full relative z-10"
      >
        <ZoomableGroup zoom={1} maxZoom={4} translateExtent={[[-400, -300], [1200, 900]]}>
          <Geographies geography={geoUrl}>
            {({ geographies }) =>
              geographies.map((geo) => (
                <Geography
                  key={geo.rsmKey}
                  geography={geo}
                  style={{
                    default: {
                      fill: '#121212', // Slightly darker for more contrast
                      stroke: '#404040', // Brighter stroke
                      strokeWidth: 0.5,
                      outline: 'none',
                    },
                    hover: {
                      fill: '#181818', 
                      stroke: '#525252',
                      strokeWidth: 0.5,
                      outline: 'none',
                    },
                    pressed: {
                      fill: '#121212',
                      outline: 'none',
                    }
                  }}
                />
              ))
            }
          </Geographies>

          {/* EESTEC Branches */}
          {lcs.map((lc, idx) => (
            <Marker 
              key={`lc-${idx}`} 
              coordinates={lc.coords}
              onMouseEnter={() => setHoveredLC(lc)}
              onMouseLeave={() => setHoveredLC(null)}
              onClick={() => {
                if (lc.website) {
                  window.open(lc.website, '_blank');
                }
              }}
            >
              <g>
                <circle 
                  r={lc.type === 'Observer' ? 4 : 6} 
                  fill={lc.type === 'Observer' ? "#9ca3af" : "#f43f5e"} // observers gray, LCs red
                  className={`drop-shadow-[0_0_10px_rgba(244,63,94,0.8)] cursor-pointer hover:fill-red-400 transition-colors animate-pulse`}
                />
                <circle 
                  r={lc.type === 'Observer' ? 2 : 3} 
                  fill="#ffffff" 
                  className="pointer-events-none"
                />
              </g>
            </Marker>
          ))}
        </ZoomableGroup>
      </ComposableMap>

      {/* Decorative background glows */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full h-full bg-red-600/5 blur-[120px] pointer-events-none rounded-full z-0" />
    </div>
  );
}
